spring.application.name=FriendList

spring.datasource.url=jdbc:postgresql://localhost:5432/friendlistdb
spring.datasource.username=postgres
spring.datasource.password=dob2060121

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true