spring.application.name=Quote01

spring.datasource.url=jdbc:postgresql://localhost:5432/sharwan
spring.datasource.username=postgres
spring.datasource.password=dob2060121

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true