spring.application.name=Library

#Database
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA Hibernate
spring.jpa.hibernate.ddl-auto=updated
